[build]
  publish = "web"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  API_URL = "https://emladis-backend.onrender.com/api"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
